controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    cart_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

cart_velocity_controller:
  ros__parameters:
    joints:
      - cart_slide
    interface_name: velocity
